name: Tests

on:
  pull_request:
  push: 
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: sudo apt update && sudo apt install clang
    - name: Create Build Environment
      run: mkdir build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=clang++ -DALLOCATORS_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j4 .

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      shell: bash
      run: ./Run_Allocators_Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ./bin/allocators-lib-tests
  
