name: Tests

on:
  pull_request:
  push: 
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: sudo apt update && sudo apt install clang
    - name: Create Build Environment
      run: mkdir build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=clang++ -DALLOCATORS_TESTS=ON

    - name: Running make
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j4 allocators-lib-tests
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{github.workspace}}/build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
         name: build
         path: ${{github.workspace}}/build
      - name: Add permissions to execute
        working-directory: ${{github.workspace}}/build
        run: chmod +x ./bin/allocators-lib-tests
      - name: Run tests 
        working-directory: ${{github.workspace}}/build
        run: ./bin/allocators-lib-tests
  
